Metatavu/pakkasmarja-web

src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/FreshDeliveryManagement.tsx
=> Modal now inherits the chosen time in reception page

package-lock.json, package.json, src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/DeliveriesScreen.tsx, src/components/deliveries/EditDelivery.tsx, src/components/products-management/CreateProduct.tsx, src/components/products-management/EditProduct.tsx, src/components/products-management/ProductsList.tsx
=> Active field in product management and no inactive products in deliveries

package-lock.json, src/components/contact/ManageContact.tsx
=> Save changes button disabled when no changes

src/components/deliveries/DeliveriesScreen.tsx
=> Icons added and title changed

package-lock.json, package.json, src/components/MqttConnector.tsx, src/components/chat/Chat.tsx, src/components/chat/ChatGroupList.tsx, src/components/chat/ChatIndex.tsx, src/components/chat/ChatThreadList.tsx, src/components/chat/ChatsContainer.tsx, src/components/contracts/ContractList.tsx, src/components/index/MainPage.tsx, src/mqtt/index.ts, src/types/index.tsx
=> Chats will now show if conversation has been read

src/components/contact/ManageContact.tsx
=> Changed vatLiable field name and options

src/components/contracts/ContractView.tsx
=> Removed profitEstimation from allFieldsFilled check

src/components/contracts/ContractView.tsx
Fixes a problem where check that ensures that contract area detail table is filled, will never let user continue
=> Production bugfix

src/components/contracts/ContractView.tsx, src/localization/fi.json, src/localization/strings.ts
=> Fixed checking logic

src/components/contracts/ContractAreaDetails.tsx
=> Added step of 0.1 to input field if its of type number

src/components/contracts/ContractAmount.tsx
=> Check if proposedAmount is not exactly undefined

src/components/contracts/ContractAmount.tsx, src/components/contracts/ContractAreaDetails.tsx
Changed ContractAmount component proposedAmount check to see if proposedAmount is specifically not undefined
=> Production update

src/components/deliveries/CreateDeliveryModal.tsx
- filtered by selected contact id instead of current logged in user id
=> Changed listProducts filtering parameters

src/components/contracts/ContractAmount.tsx, src/components/deliveries/CreateDeliveryModal.tsx
Bugfix for listProducts listing products based on logged in user instead of selected farmer.
=> Bugfix update

package-lock.json, package.json, src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/DeliveriesScreen.tsx, src/components/generic/BasicLayout.tsx, src/components/generic/MenuContainer.tsx, src/components/index/MainPage.tsx, src/components/opening-hours-management/OpeningHoursScreen.tsx, src/localization/fi.json, src/localization/strings.ts, src/utils/application-roles.tsx, tsconfig.json
=> Feature 174 opening hours management screen

package-lock.json, package.json, src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/DeliveriesScreen.tsx, src/components/opening-hours-management/OpeningHoursScreen.tsx
=> Added bug fixes

src/components/deliveries/DeliveriesScreen.tsx, src/components/generic/MenuContainer.tsx, src/components/opening-hours-management/OpeningHoursScreen.tsx
=> Made fixes to privileges logic and some code cleanup

package-lock.json, package.json, src/components/login/Login.tsx
- TODO: Keycloak should be updated to the project
Resolves #186
=> Removed login iframe checks from keycloak

package-lock.json, src/components/generic/PriceChart.tsx
=> Alv price is now visible when making delivery

src/components/deliveries/FreshDeliveryManagement.tsx, src/components/deliveries/SalesForecastTable.tsx, src/components/deliveries/StorageTable.tsx
=> Tables now scale properly

src/components/deliveries/CreateDelivery.tsx, src/components/opening-hours-management/OpeningHoursScreen.tsx
=> Bug 193 opening hour dates are not whole dates

src/components/deliveries/CreateDelivery.tsx
=> Price is now fetched from selected day

src/components/chat/Chat.tsx
=> Bug 198 deleting chat messages

src/components/deliveries/FrozenDeliveryManagement.tsx
=> Took a while to find right modal but selected date is now passed in as a modal prop when making frozen deliveries

src/components/contract-management/ContractManagementList.tsx, src/localization/fi.json, src/localization/strings.ts
=> Contracts can now be edited from the table

src/components/contract-management/EditContract.tsx
=> Changed year to be defined from existing contract

src/components/contract-management/EditContract.tsx
=> Added string option to input field rendering types

src/components/contracts/ContractView.tsx
- Fixes bug where sapId was not visible in edit contracts view
=> Production update 12.5.2021

src/components/chat/ChatGroupList.tsx, src/components/chat/ChatThreadList.tsx
=> Added ordering

src/components/contracts/ContractView.tsx
- Enhanced chat thread sorting
=> Production update 20.5.2021

package-lock.json, src/components/chat/Chat.tsx, src/components/chat/ChatIndex.tsx, src/components/chat/ChatThreadList.tsx, src/components/chat/ChatsContainer.tsx
Added back button to question groups
Improved functionality of chat windows
=> Added labels to chat windows

package-lock.json, package.json, src/components/contracts/ContractTerms.tsx, src/components/operations-management/OperationsList.tsx, src/localization/fi.json, src/localization/strings.ts
=> Added feature and formatted code

src/components/deliveries/ManageDeliveryModal.tsx, src/components/operations-management/OperationReport.tsx, src/components/operations-management/OperationsList.tsx, src/utils/operations.ts
- fixed bug where farmer planned delivery could not be edited by Pakkasmarja
- fixed bug where delivery time field resetting when delivery is modified
- formatted code
=> Multiple fixes

src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/EditDelivery.tsx
=> Filtered out OTHER delivery place

src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/ManageDeliveryModal.tsx, src/localization/fi.json, src/localization/strings.ts, src/styles/common.scss
=> added support for contract amount limits

src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/FreshDeliveryManagement.tsx, src/components/deliveries/SalesForecastTable.tsx, src/utils/table-data-utils.ts
=> Feature 248 quality class table to free field

src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/FreshDeliveryManagement.tsx, src/components/deliveries/ManageDeliveryModal.tsx
=> Feature 254 free field table tweaks

src/components/deliveries/ManageDeliveryModal.tsx
=> tweaked showing of contract quantities

src/components/deliveries/ManageDeliveryModal.tsx
- fixed error where already accepted delivery's delivered amount would be calculated twice to the total delivered amount
=> Production update 28.7.2021

package-lock.json, src/components/contract-management/ContractManagementList.tsx
=> Removed redundant fetch

package-lock.json, src/components/contract-management/ContractManagementList.tsx, src/components/deliveries/ManageDeliveryModal.tsx
- fixed issue where wrong contract document template was shown when contract template was edited from contract management
=> Production update 16.8.2021

src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/EditDelivery.tsx, src/components/deliveries/ManageDeliveryModal.tsx, src/components/deliveries/ProposalAcceptModal.tsx, src/components/deliveries/ViewModal.tsx, src/types/index.tsx
=> Added separate logic for done delivery creation and fixed typos

src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/IncomingDeliveries.tsx, src/components/generic/asynchronous-button.tsx, src/types/index.tsx
=> Added checkboxes to delivery start modal

package-lock.json, package.json, src/components/deliveries/ManageDeliveryModal.tsx, src/components/operations-management/OperationsList.tsx, src/localization/fi.json, src/localization/strings.ts, src/utils/operations.ts
=> Added orange boxes and fixed broken logic

src/components/contract-management/ContractManagementList.tsx, src/components/contract-management/EditContract.tsx, src/components/contract-management/xlsx-contract-preview.tsx, src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/ManageDeliveryModal.tsx, src/components/itemgroups-management/EditItemGroupDocument.tsx, src/localization/fi.json
=> Added orange box and fixed delivery management logic

src/components/itemgroups-management/EditItemGroupDocument.tsx
- also cleaned up the component
Resolves #284
=> Fixed contract document template loading

src/components/contracts/ContractParties.tsx
Added SAP ID to farmer info in contract parties
=> Production update #3 24.5.2022

src/components/deliveries/ManageDeliveryModal.tsx
Fixed delivery management status logic
=> Production update 25.5.2022

src/components/App.tsx, src/components/generic/MenuContainer.tsx, src/components/index/MainPage.tsx
=> Removed chat and chat management

src/components/App.tsx, src/components/deliveries/CreateDelivery.tsx, src/components/deliveries/EditDelivery.tsx, src/components/generic/MenuContainer.tsx, src/components/index/MainPage.tsx, src/utils/index.ts
- limits delivery options to Suonenjoki when delivery category is fresh
Resolves #305
=> Feature-305-limit-fresh-delivery-place-options-to-Suonenjoki

src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/FreshDeliveryManagement.tsx, src/components/generic/PriceChart.tsx, src/localization/fi.json
=> Removed suggestion option from delivery management

src/components/contract-management/ContractManagementList.tsx, src/components/contract-management/EditContractDocument.tsx, src/components/contract-management/contract-preview-table.tsx, src/components/contract-management/xlsx-contract-preview.tsx, src/components/deliveries/FreshDeliveryManagement.tsx, src/components/deliveries/FrozenDeliveryManagement.tsx, src/localization/fi.json
- also changed add button texts in delivery management views
Resolves #318
=> Improved contract batch importer

src/components/contract-management/xlsx-contract-preview.tsx, src/components/generic/asynchronous-button.tsx
- also fixed AsyncButton component life cycle issue and some styling
=> Fixed erroneous responses from createContract

src/components/deliveries/CreateDeliveryModal.tsx
=> Added proposal option

src/components/deliveries/CreateDeliveryModal.tsx, src/components/deliveries/ManageDeliveryModal.tsx
=> Filtered out other delivery places than suonenjoki from fresh delivery management

package-lock.json, package.json, src/components/login/Login.tsx
=> Bumped Keycloak client version to 23.0.7
